### ISSUE TITLE
同项目求更新

### ISSUE THREAD

**Issue by 737069384** [max-min/cmpp3.0#1]

**Comment by max-min** [comment]
最近工作也有事，会支持更新的。

**Comment by 737069384** [comment]
有联系方式吗 有些问题想问您

**Comment by max-min** [comment]
有什么问题？

**Comment by 737069384** [comment]
这个怎么用你的接口

**Comment by max-min** [comment]
看cmppManager,里面读取网关的基本配置信息后，就可以调用submitMessage进行发送短信了。

**Comment by 737069384** [comment]
Traceback (most recent call last):                                                                  
  File "cmpp_manager.py", line 97, in <module>                                                      
    cmppManager.submitMessage("Helloworld", "10644xxxxx2531")                                       
  File "cmpp_manager.py", line 28, in submitMessage                                                 
    ret,sockFd = cmppHandle.connectISMG(cmppManager.IP, cmppManager.PORT)                           
  File "/home/cmpp_handle.py", line 16, in connectISMG                                              
    if  sockFd > 0 :                                                                                
TypeError: unorderable types: socket() > int()
